from_numpy_matrix doesnt exist
G = nx.from_numpy_matrix(adj_matrix) gives error AttributeError: module 'networkx' has no attribute 'from_numpy_matrix'